### PR TITLE
fix: Resolve the error coming up during local project setup

### LINKED ISSUE #53: [BUG] Error during project installation
When we run the project by using npm run dev it is giving us unhandled runtime error

Go to the terminal
Type npm run dev
Then go to the browser

When the project is fully loaded it is giving us
image

### PR DESCRIPTION
**Pull request by keerthi538**
## 🛠️ Fixes Issue

Closes #53 

## 👨‍💻 Changes proposed

- Use of `typeof window !== 'undefined'` creates an error. Refer https://nextjs.org/docs/messages/react-hydration-error
- Restructured the `useWindowDimensions` hook and used the same logic inside useEffect so that this logic runs only on client

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

File: hooks/useWindowDimensions.js [hunk 1]
```diff
@@ -1,10 +1,12 @@
 import { useState, useEffect } from 'react';
 
-export default function useWindowDimensions() {
-
-  const hasWindow = typeof window !== 'undefined';
+const initDimensions = {
+  height: 0,
+  width: 0,
+};
```
Comment (mrcoder991) [inline hooks/useWindowDimensions.js:6]: The `initDimensions` object is a good addition. This ensures initial state is predictable.

File: hooks/useWindowDimensions.js [hunk 2]
```diff
@@ -13,18 +15,21 @@ export default function useWindowDimensions() {
```
Comment (mrcoder991) [inline hooks/useWindowDimensions.js:14]: In the `useWindowDimensions` function, you don't need to pass `hasWindow` to `getWindowDimensions` since it's already defined inside `useEffect`. The `hasWindow` check can just be used directly.

**Review by mrcoder991 — COMMENTED** [review]
Good refactor to avoid `typeof window !== 'undefined'` error. A few improvements suggested below
